<script setup lang="ts">
import { computed, ref } from 'vue'
import { useCircuitStore } from '../../stores/circuit'
import { useWorkspaceStore } from '../../stores/workspace'
import { componentCatalog, getDefinition } from '../../data/editorCatalog'
import { useStationStore } from '../../stores/station'
import { useInstrumentStore } from '../../stores/instrument'
import { useUiStore } from '../../stores/ui'
import HardwareStatus from '../HardwareStatus.vue'
import ValidationNotice from '../ValidationNotice.vue'
const circuit = useCircuitStore(), station = useStationStore(), instrument = useInstrumentStore(), ui = useUiStore()
const workspace = useWorkspaceStore()
const selected = computed(() => circuit.graph?.modules.find((module) => module.id === workspace.selectedModuleId))
const definition = computed(() => selected.value && getDefinition(selected.value.type))
const source = ref(''), destination = ref(''), addType = ref('DIGITAL_SWITCH')
const endpoints = computed(() => circuit.graph?.modules.flatMap((module) => (getDefinition(module.type)?.ports ?? []).map((port) => ({ ...port, id: `${module.id}.${port.id}` }))) ?? [])
function edit(action: () => void) { try { action(); workspace.editError = '' } catch (error) { workspace.editError = error instanceof Error ? error.message : 'Circuit edit failed.' } }
function position(axis: 'x' | 'y' | 'z', event: Event) { if (selected.value) { const module = selected.value; edit(() => circuit.moveModule(module.id, { x: module.position?.x ?? 0, y: module.position?.y ?? 0, z: module.position?.z ?? 0, [axis]: Number((event.target as HTMLInputElement).value) })) } }
function select(event: Event) { const value = (event.target as HTMLSelectElement).value; value === '' ? station.useSimulation() : station.selectStation(value) }
</script>
<template>
  <section class="inspector-section"><h2>Component editor</h2>
    <label>Add component at origin<select v-model="addType"><option v-for="item in componentCatalog" :key="item.type" :value="item.type">{{ item.name }}</option></select></label><button @click="edit(() => workspace.selectModule(circuit.placeModule(addType, { x: 0, y: 0, z: 0 })))">Add component</button>
    <label>Select component<select :value="workspace.selectedModuleId || ''" @change="workspace.selectModule(($event.target as HTMLSelectElement).value || null)"><option value="">None</option><option v-for="module in circuit.graph?.modules" :key="module.id" :value="module.id">{{ module.id }} · {{ module.type }}</option></select></label>
    <template v-if="selected"><strong>{{ selected.id }}</strong><p class="window-note">{{ definition?.visualOnly ? 'Visual structure only; no electrical source or node map.' : 'Functional logical ports; physical pin mapping and execution are separate.' }}</p>
      <div class="property-coordinates"><label v-for="axis in (['x', 'y', 'z'] as const)" :key="axis">{{ axis.toUpperCase() }}<input :aria-label="'Component ' + axis.toUpperCase()" type="number" step="0.5" :value="selected.position?.[axis] ?? 0" @change="position(axis, $event)" /></label></div>
      <label>Rotation (degrees)<input type="number" :value="selected.rotation ?? 0" step="90" @change="edit(() => circuit.rotateModule(selected!.id, Number(($event.target as HTMLInputElement).value) - (selected!.rotation ?? 0)))" /></label>
      <label v-for="parameter in definition?.parameters" :key="parameter.key">{{ parameter.label }}<input v-if="parameter.kind === 'boolean'" type="checkbox" :checked="Boolean(selected.properties?.[parameter.key] ?? definition?.defaults[parameter.key])" @change="edit(() => circuit.updateModuleProperties(selected!.id, { [parameter.key]: ($event.target as HTMLInputElement).checked }))" /><input v-else type="number" :min="parameter.min" :max="parameter.max" :step="parameter.kind === 'integer' ? 1 : 'any'" :value="Number(selected.properties?.[parameter.key] ?? definition?.defaults[parameter.key])" @change="edit(() => circuit.updateModuleProperties(selected!.id, { [parameter.key]: Number(($event.target as HTMLInputElement).value) }))" /></label>
      <div class="component-edit-actions"><button @click="edit(() => circuit.rotateModule(selected!.id))">Rotate 90°</button><button @click="circuit.removeModule(selected!.id)">Delete component</button><button v-if="definition?.memoryContract" @click="ui.openWindow('hex-editor')">Edit memory image</button></div>
      <p v-if="!definition" class="window-note">Unknown imported type retained. Port map is unavailable.</p>
    </template>
  </section>
  <section class="inspector-section"><h2>Logical connections</h2><label>Source port<select v-model="source"><option value="">Choose source</option><option v-for="port in endpoints.filter(p => p.direction !== 'input')" :key="port.id" :value="port.id">{{ port.id }} · {{ port.width || 1 }} bit</option></select></label><label>Destination port<select v-model="destination"><option value="">Choose destination</option><option v-for="port in endpoints.filter(p => p.direction !== 'output')" :key="port.id" :value="port.id">{{ port.id }} · {{ port.width || 1 }} bit</option></select></label><button :disabled="!source || !destination" @click="edit(() => circuit.connectPorts(source, destination))">Connect ports</button><ul class="connection-list"><li v-for="(wire, index) in circuit.graph?.connections" :key="index"><code>{{ wire.source }} → {{ wire.destination }}</code><button :aria-label="'Disconnect ' + wire.source + ' to ' + wire.destination" @click="circuit.disconnectPorts(wire.source, wire.destination)">Disconnect</button></li></ul><p v-if="workspace.editError" role="alert" class="notice error">{{ workspace.editError }}</p><p class="window-note">Connections are explicit graph edges. Geometry, overlap and breadboard holes never connect components.</p></section>
  <section class="inspector-section"><h2>Circuit</h2><label>Project name<input :value="circuit.current?.name || ''" :disabled="!circuit.current" maxlength="200" @change="circuit.renameCurrent(($event.target as HTMLInputElement).value)" /></label><label v-if="circuit.drafts.length > 1">Session drafts<select :value="circuit.activeId || ''" @change="circuit.openDraft(($event.target as HTMLSelectElement).value)"><option v-for="draft in circuit.drafts" :key="draft.id" :value="draft.id">{{ draft.name }}</option></select></label><div class="inspector-counts"><span>{{ circuit.graph?.modules.length || 0 }} components</span><span>{{ circuit.graph?.connections.length || 0 }} wires</span><code>schema 1.0</code></div><button class="accent-button" :disabled="!circuit.graph || circuit.validating" @click="circuit.validateCurrent()">{{ circuit.validating ? 'Validating…' : 'Validate graph' }}</button><ValidationNotice /></section>
  <section class="inspector-section"><h2>Execution target</h2><label>Mode / station<select :value="station.stationId || ''" @change="select"><option value="">Local simulation</option><option v-if="station.stationId && !station.selected" :value="station.stationId">{{ station.stationId }} · offline</option><option v-for="target in station.stations" :key="target.station_id" :value="target.station_id">{{ target.station_id }} · {{ target.mode }} · {{ target.state }}</option></select></label><div class="target-status"><HardwareStatus /><button :disabled="station.loading" @click="station.refresh()">{{ station.loading ? 'Refreshing…' : 'Refresh' }}</button></div><p v-if="station.error" class="notice error" role="alert">{{ station.error }}</p><p class="window-note">Events: {{ ui.connectionState }}. Local simulation mode does not imply that an execution engine is connected.</p></section>
  <section class="inspector-section"><div class="console-heading"><h2>Event console</h2><button @click="instrument.clearConsole()">Clear</button></div><ol class="event-console" aria-label="Event console"><li v-for="entry in instrument.entries" :key="entry.id" :class="entry.level"><time>{{ entry.time }}</time>{{ entry.message }}</li><li v-if="!instrument.entries.length">No events yet.</li></ol></section>
</template>
