<script setup lang="ts">
import { useCircuitStore } from '../../stores/circuit'
import { useStationStore } from '../../stores/station'
import { useInstrumentStore } from '../../stores/instrument'
import { useUiStore } from '../../stores/ui'
import HardwareStatus from '../HardwareStatus.vue'
import ValidationNotice from '../ValidationNotice.vue'
const circuit = useCircuitStore(), station = useStationStore(), instrument = useInstrumentStore(), ui = useUiStore()
function select(event: Event) { const value = (event.target as HTMLSelectElement).value; value === '' ? station.useSimulation() : station.selectStation(value) }
</script>
<template><section class="inspector-section"><h2>Circuit</h2><label>Project name<input :value="circuit.current?.name || ''" :disabled="!circuit.current" maxlength="200" @change="circuit.renameCurrent(($event.target as HTMLInputElement).value)" /></label><label v-if="circuit.drafts.length > 1">Session drafts<select :value="circuit.activeId || ''" @change="circuit.openDraft(($event.target as HTMLSelectElement).value)"><option v-for="draft in circuit.drafts" :key="draft.id" :value="draft.id">{{ draft.name }}</option></select></label><div class="inspector-counts"><span>{{ circuit.graph?.modules.length || 0 }} components</span><span>{{ circuit.graph?.connections.length || 0 }} wires</span><code>schema 1.0</code></div><button class="accent-button" :disabled="!circuit.graph || circuit.validating" @click="circuit.validateCurrent()">{{ circuit.validating ? 'Validating…' : 'Validate graph' }}</button><ValidationNotice /></section><section class="inspector-section"><h2>Execution target</h2><label>Mode / station<select :value="station.stationId || ''" @change="select"><option value="">Local simulation</option><option v-if="station.stationId && !station.selected" :value="station.stationId">{{ station.stationId }} · offline</option><option v-for="target in station.stations" :key="target.station_id" :value="target.station_id">{{ target.station_id }} · {{ target.mode }} · {{ target.state }}</option></select></label><div class="target-status"><HardwareStatus /><button :disabled="station.loading" @click="station.refresh()">{{ station.loading ? 'Refreshing…' : 'Refresh' }}</button></div><p v-if="station.error" class="notice error" role="alert">{{ station.error }}</p><p class="window-note">Events: {{ ui.connectionState }}. Local simulation mode does not imply that an execution engine is connected.</p></section><section class="inspector-section"><div class="console-heading"><h2>Event console</h2><button @click="instrument.clearConsole()">Clear</button></div><ol class="event-console" aria-label="Event console"><li v-for="entry in instrument.entries" :key="entry.id" :class="entry.level"><time>{{ entry.time }}</time>{{ entry.message }}</li><li v-if="!instrument.entries.length">No events yet.</li></ol></section></template>
